---
name: Publish to PyPI
"on":
  push:
    tags:
      - "v*"
jobs:
  publish-to-pypi:
    name: Build and Publish Python Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Poetry and Dynamic Versioning
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry self add poetry-dynamic-versioning
      - name: Install project dependencies
        run: poetry install --no-root
      - name: Build package
        run: poetry build
      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish
