---
name: Release Please
"on":
  push:
    branches:
      - main
jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Release Please Action
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: python
          package-name: utils-repl
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug
            Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":true}]'
